app:
  name: "service"
  environment: "local"
  port: "8080" 
  debug: true

postgres:
  host: "localhost"
  port: "5432"
  user: "default_user"
  password: "default_pass"
  dbname: "postgres"

api_server:
  host: "0.0.0.0"
  port: "8080"

logger:
  level: 'debug'