app:
  name: "service"
  environment: "local"
  port: "8080" 
  debug: true

postgres:
  host: "postgres"
  port: "5432"
  user: "default_user"
  password: "default_pass"
  dbname: "default_dbname"

api_server:
  host: "0.0.0.0"
  port: "8080"

logger:
  level: 'debug'

redis: 
  addres: "redis:6379"
  password: ""
  db: 1

nats:
  url: "nats://nats:4222"